[package]
name = "neuron"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'

[dependencies]
serde = "1"
candid = "0.7.4"
ic-kit = "0.4.3"
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
